name = "MPBUtils"
uuid = "a5feb4ea-5495-4677-96f8-dddb76c9eb4c"
authors = ["Thomas Christensen <tchr@mit.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
